config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#root'
  devise_for :users
  
  namespace :api, defaults: {format: :json} do
    resources :projects do
      resources :tasks
    end
  end
  resources :users, only: [:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  validates :name, presence: true
  belongs_to :user
  has_many :tasks, dependent: :destroy
end

app/models/task.rb
class Task < ApplicationRecord
  validates :name, presence: true;
  validates :completed, inclusion: { in: [ true, false ] }

  belongs_to :project

  after_initialize :set_boolean

  def set_boolean
    self.completed || self.completed = false
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :projects
  
  has_many :tasks,
  through: :projects,
  source: :tasks
end

app/controllers/api/projects_controller.rb
class Api::ProjectsController < ApplicationController
  before_action :authenticate_user!

  def index
    @projects = current_user.projects.includes(:tasks)
    render json: @projects
  end

  def create
    @project = Project.new(project_params)
    @project.user = current_user
    @project.save
    render :show
  end

  private

  def project_params
    params.require(:project).permit(:name)
  end
end

app/controllers/api/tasks_controller.rb
class Api::TasksController < ApplicationController
  before_action :authenticate_user!

  def index
    @tasks = Project.find(params[:project_id]).tasks
    render json: @tasks
  end

  def create
    @task = Task.new(task_params)
    @task.project_id = params[:project_id] 
    @task.save
    render :show
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    render :show
  end

  private

  def task_params
    params.require(:task).permit(:name, :completed, :project_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def root
    render :root
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @tasks = @user.tasks.select{ |task| task.completed == true }
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManagerApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%
=begin%>
 <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %> 
<%
=end%>

    <p class="nav-bar">
      <% if user_signed_in? %>
        Logged in as <%= link_to current_user.username.capitalize, user_url(current_user) %>.
        <%= link_to "Home", root_url %>
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
        <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
    </p>
    
    <%= yield %>
  </body>
</html>

app/views/static_pages/root.html.erb
<body class="index">
  <h1 style="color:white">Your Projects</h1>

  <div class="projects-container">
    <%= react_component('Projects') %>
  </div>
</body>

app/views/users/show.html.erb
<h1> User Profile </h1>

<p> Name: <%= @user.username.capitalize %> </p>
<p> Email: <%= @user.email %> </p>

<div>
  <h2>Completed Tasks</h2>
  <ul class="bulleted">
    <% @tasks.each do |task| %>
      <li> <%= task.name %> </li>
    <% end %>
  <ul>
</div>